# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd752cef4b46eb1adb2bdb7c5722988e81e895581cebc1e8e697aaa9353756ab523e4655a5dd3fedf94f9b2e60f3647dd29fda0719c9d57dbd8085a444bc59ac

test:
  secret_key_base: f6849ca6ff06423a6ea34466ff18d868fb774f0103c8d7c6217f3ef3ff106dd74b24bec12c62c11e77287e35a13619c1fad0b8e138823f742b38ef945ad36244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
